services:
  spark-master:
    image: spark-master:2.4.0
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark-network
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      
  spark-worker:
    image: spark-worker:2.4.0
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - shared-workspace:/opt/workspace
    env_file: ./spark/env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker"
    networks:
      - spark-network
      
  livy:
    image: livy:0.7.0-incubating
    container_name: livy
    hostname: livy
    ports:
      - "8998:8998"
    networks:
      - spark-network
  
  solr:
    image: solr:latest
    container_name: solr
    hostname: solr
    ports:
     - "8983:8983"
    networks:
     - spark-network
    #volumes:
     #- solr_data:/var/solr
    #command:
      #- solr-precreate
      #- solr-core

networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
